[tool.poetry]
name = "necstdb"
version = "0.2.10"
description = "Database for NECST."
authors = ["Kaoru Nishikawa <k.nishikawa@a.phys.nagoya-u.ac.jp>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ogawa-ros/necstdb"
repository = "https://github.com/ogawa-ros/necstdb"

classifiers = [
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"

numpy = ">=1.26.4,<3.0"
pandas = ">=2.2.2,<3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
black = "^24.3"
flake8 = "^7.0"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
